# Generated by Django 5.0.1 on 2024-01-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkPatternsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('dark_pattern_label', models.CharField(max_length=255)),
                ('dark_text', models.TextField()),
            ],
        ),
    ]
