# Generated by Django 5.0.1 on 2024-02-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlApi', '0003_dprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dprequest',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
