# Generated by Django 5.0.1 on 2024-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlApi', '0002_darkpatternsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
