# Generated by Django 5.0.6 on 2024-06-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faqdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkPatternsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('dark_pattern_label', models.CharField(max_length=255)),
                ('dark_text', models.TextField()),
            ],
        ),
    ]
