# Generated by Django 5.0.6 on 2024-06-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarkPatternsData',
        ),
    ]
