# Generated by Django 5.0.6 on 2024-07-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_apikey_delete_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
